### ISSUE TITLE
你的工作阶段因不明原因而异常终止

### ISSUE THREAD

**Issue by takosantakusan** [Ayanaminn/N46Whisper#112]
运行Whisper阶段到识别中一出现0%就会跳失败，原本操作都是可以使用的!
点击查看后显示这些

Jan 31, 2025, 8:54:13 PM	WARNING	WARNING:root:kernel f7f2a14b-e2bb-4e85-bbe8-0eb0f4298647 restarted
Jan 31, 2025, 8:54:13 PM	INFO	KernelRestarter: restarting kernel (1/5), keep random ports
Jan 31, 2025, 8:54:10 PM	WARNING	Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

求解决方法!感恩!

**Comment by zihan0324** [comment]
遇到了同样的问题，是libcudnn的版本不对，可以新建单元格后先执行以下命令查看一下libcudnn的版本
```
!ls /usr/lib/x86_64-linux-gnu/ | grep cudnn
```
应该显示的是：
```
libcudnn_adv.so
libcudnn_adv.so.9
libcudnn_adv.so.9.2.1
libcudnn_cnn.so
libcudnn_cnn.so.9
...
```
因此，需要重新安装**libcudnn8**，新建一个单元格执行以下命令
```
!apt remove --purge -y libcudnn9 libcudnn9-dev
!apt autoremove -y
!apt update
!apt install -y libcudnn8 libcudnn8-dev
```

再执行「运行Whisper」那一格的代码应该就行了

**Comment by takosantakusan** [comment]
> 遇到了同樣的問題，是libcudnn的版本不對，可以新建單元格後先執行查看一下libcudnn的版本
> 
> ```
> !ls /usr/lib/x86_64-linux-gnu/ | grep cudnn
> ```
> 
> 應該顯示的是：
> 
> ```
> libcudnn_adv.so
> libcudnn_adv.so.9
> libcudnn_adv.so.9.2.1
> libcudnn_cnn.so
> libcudnn_cnn.so.9
> ...
> ```
> 
> 因此，需要重新安裝**libcudnn8**，新建一個儲存格執行
> 
> ```
> !apt remove --purge -y libcudnn9 libcudnn9-dev
> !apt autoremove -y
> !apt update
> !apt install -y libcudnn8 libcudnn8-dev
> ```
> 
> 再執行「運行 Whisper」那一格程式碼應該就執行了


照做后已解决!超感谢!

**Comment by zyh310** [comment]
也可以把 ctranslate2 的版本从 4.4.0 改成 4.5.0，会更快一些

**Comment by latinisation** [comment]
谢谢大伙的提问跟答复！！！上周我还一直以为是我那个视频有问题
